### ISSUE TITLE
Create internal R function to transform quantile model-output data to scoringutils-compatible format

### ISSUE THREAD

**Issue by bsweger** [hubverse-org/hubEvals#22]
(formerly part of #12)

Create an internal data transformation function in hubEvals that will transform quantile model-output data into a format that can be successfully converted to a scoringutils `forecast` object: https://epiforecasts.io/scoringutils/dev/reference/as_forecast.html.

This is not a user-facing function. Instead, it will be invoked by the publicly-accessible function described in #11.

A good source of test data for this function is the `forecast_outputs` data object in the `hubExamples` repo (filtering on `output_type` == `quantile`)

https://github.com/Infectious-Disease-Modeling-Hubs/hubExamples/blob/main/data/forecast_outputs.rda 

Definition of done:

- [ ] A new R function called `transform_quantile_model_output`
- [ ] Corresponding unit test(s)

**Comment by nickreich** [comment]
closed by #27
