### ISSUE TITLE
Create internal R function to transform pmf model-output data to scoringutils-compatible format

### ISSUE THREAD

**Issue by bsweger** [hubverse-org/hubEvals#24]
(formerly part of https://github.com/Infectious-Disease-Modeling-Hubs/hubEvals/issues/12)

Similar to other hubverse-supported output types (_e.g._, #23, #24, #25), we will need an internal transformation function in hubEvals to handle transforming pmf model-output data into the scoringutils forecast object: https://epiforecasts.io/scoringutils/dev/reference/as_forecast.html.

However, scoringutils does not yet support the pmf model output type ([related issue](https://github.com/epiforecasts/scoringutils/issues/604)), so we're not yet able to do this data conversion.

In the meantime, we can create the internal function for transforming pmf output data, but use it to alert hubverse users that pmf scoring is not yet implemented (instead of doing the actual data transformation).

This is not a user-facing function. Instead, it will be invoked by the publicly-accessible function described in https://github.com/Infectious-Disease-Modeling-Hubs/hubEvals/issues/11.

Definition of done:

- [ ] A new R function called `transform_pmf_model_output` that returns a "not yet implemented" message to be caught by upstream `hubEval` wrapper functions (#11) and passed back to the user
- [ ] Corresponding unit test(s)

**Comment by elray1** [comment]
Noting that the pmf functionality is now in scoringutils
