### ISSUE TITLE
Create internal R function to transform mean and median model-output data to scoringutils-compatible format

### ISSUE THREAD

**Issue by bsweger** [hubverse-org/hubEvals#25]
(formerly part of https://github.com/Infectious-Disease-Modeling-Hubs/hubEvals/issues/12)

Create an internal data transformation function in hubEvals that will transform mean and median model-output data into a format that can be successfully converted to a scoringutils forecast object: https://epiforecasts.io/scoringutils/dev/reference/as_forecast.html (scoringutils classifies both mean and median forecasts as a `point` forecast).

This is not a user-facing function. Instead, it will be invoked by the publicly-accessible function described in https://github.com/Infectious-Disease-Modeling-Hubs/hubEvals/issues/11.

A good source of test data for this function is the forecast_outputs data object in the `hubExamples` repo (filtering on `output_type == mean` and `output_type == median`)

https://github.com/Infectious-Disease-Modeling-Hubs/hubExamples/blob/main/data/forecast_outputs.rda

Definition of done:

- [ ] A new R function called `transform_point_model_output`
- [ ] Corresponding unit test(s)

**Comment by elray1** [comment]
couple of quick notes:

- consider names like `transform_point_model_out`
- we should be able to get away without requiring the column names `location`, `target_end_date`, and `horizon`
