### ISSUE TITLE
 Consistent argument name for a model output tbl

### ISSUE THREAD

**Issue by LucieContamin** [hubverse-org/hubEvals#31]
It was decided in dev meeting to standardized argument name for model output tbls to `model_out_tbl`. The `hubEvals::transform_point_model_out` need to be updated accordingly

**Comment by elray1** [comment]
It looks like this function is already using the correct name here: https://github.com/hubverse-org/hubEvals/blob/5c7b5702b87a31026549d83f261f750d80823f43/R/transform_point_model_out.R#L13
