### ISSUE TITLE
update examples from hubExamples

### ISSUE THREAD

**Issue by zkamvar** [hubverse-org/hubEvals#61]
> That is, https://github.com/hubverse-org/hubExamples/pull/39 changed the example names, so they should be changed here.

_Originally posted by @zkamvar in https://github.com/hubverse-org/hubEvals/issues/60#issuecomment-2460590493_
            

Of course, since this package is not yet released, it's best to wait for a release of hubExamples before updating.

**Comment by elray1** [comment]
See also #59

**Comment by elray1** [comment]
I'm closing this as being part of #59; it's not actually possible to separate this item from the other to-dos in that issue.
